### ISSUE TITLE
adding a simple GUI User interaction for the Diagnosing breast cancer excersise with Tkinter in python

### ISSUE THREAD

**Issue by Ndery-cloud** [chris-lovejoy/CodingForMedicine#29]
after training the model using Randomforest classifier i have added a simple GUI using tkinter in python, the GUI takes random user inputs based on 3 predection values and delivers then an Output M or B for the daignosis.

**Comment by chris-lovejoy** [comment]
Awesome! sounds great. Do you have the code? Want to submit a PR?

**Comment by Ndery-cloud** [comment]
yes i have the code but its all python files (.py) and not jupyter files since i converted the jupyter files from the breastcancer diagnosis into python scripts and created (modell.py, main.py, and GUI.py) as an application so to speak :)

**Comment by chris-lovejoy** [comment]
okay nice - well if you want to share as an educational exercise in some way, just let us know :)
