### ISSUE TITLE
Stroke Prediction Exercise

### ISSUE THREAD

**Issue by lawrenceadams** [chris-lovejoy/CodingForMedicine#4]
Start work on Stroke Prediction exercise at [over here](https://github.com/lawrenceadams/CodingForMedicine/tree/stroke-prediction) ([file](https://github.com/lawrenceadams/CodingForMedicine/blob/stroke-prediction/exercises/Stroke_Prediction_Model.ipynb))

Rough outline for things to cover/notebook structure:
- Get data / load into runtime / imports etc.
- Data Exploration
- Build models
- Explore Accuracy Paradox
   - Look at better alternatives, e.g. F1/AUC/etc
- Overfitting and underfitting

Anything else worth going into @chris-lovejoy ?

Is it possible to be added as a collaborator to the repo?

**Comment by chris-lovejoy** [comment]
Potentially some techniques for dealing with class imbalance? e.g. stratified K fold cross validation, upsampling (and maybe downsampling) techniques like SMOTE, etc. Although I wouldn't consider these core, so could be things to just mention + refer to other resources, perhaps have as an 'extra activity'

Re: collaborator - sure thing! I'll add you now

**Comment by lawrenceadams** [comment]
Yep was going to go through the above and a briefer look at SMOTE etc.

Many thanks!

**Comment by chris-lovejoy** [comment]
have just done a PR on your branch + added you to the readme. Was going to make a few edits / suggestions within the doc itself if that's okay?

**Comment by chris-lovejoy** [comment]
have just done a PR on your branch + added you to the readme. Was going to make a few edits / suggestions within the doc itself if that's okay?

**Comment by chris-lovejoy** [comment]
closing this issue as full draft of exercise now complete
