### ISSUE TITLE
Making breast_cancer_features exercise more interactive

### ISSUE THREAD

**Issue by chris-lovejoy** [chris-lovejoy/CodingForMedicine#5]
The [breast cancer features exercise](https://github.com/chris-lovejoy/CodingForMedicine/blob/main/exercises/Breast_cancer_features.ipynb) is only 'loosely' interactive. It encourages users to manipulate the code, but has no actual requirements for this and can run front-to-back without modification. Therefore, this exercise does not currently pass Principle 2 (of being interactive).

To improve it, there should be more explicit "stop points" where users are prompted to modify the code. For example, this could describe functions that *could* be used, but which aren't yet implemented - and invite the user to implement them and play around.

**Comment by lawrenceadams** [comment]
Dim question, what are the other Principles of being interactive? 

Will modify my exercise to match

**Comment by chris-lovejoy** [comment]
So I added three principles to the README - interactive, highly descriptive and easy to run
