### ISSUE TITLE
Optimal Data Source?

### ISSUE THREAD

**Issue by lawrenceadams** [chris-lovejoy/CodingForMedicine#7]
@chris-lovejoy Do you have a particular idea of how you want students to get data?

My current method uses the kaggle CLI, however I thought it was surprised by how much of a faff it is to use (having to create an account, manually pasting a .json file into ~/.kaggle etc.) - not beginner friendly in my opinion. 

Did you invision just including the data within the repo, or having the notebook grab it from a source?

Not hugely important but I suppose it would be ideal to have a uniform approach between notebooks.

**Comment by chris-lovejoy** [comment]
Yes, I agree that kaggle CLI is less user friendly. My current thinking on this is to download the data via a link and then put it in the right location for the notebook to load (which I think is easier when local compared to when on e.g. google colab - but I put a description for colab in the ['setting up' notebook](https://github.com/chris-lovejoy/CodingForMedicine/blob/main/exercises/Setting_up_Jupyter_Notebook.ipynb) which hopefully explains it).

I did think about storing data in the repo, but I think this really depends on the type of data. Sometimes it would be fine, but other times the size of data would be prohibitive - so I opted not to do so as a general practice.

What do you think?

**Comment by lawrenceadams** [comment]
I agree, I think it's cleaner to not include it within this repo, gets messy and large with all of them I imagine!

Think it is best for it to be "automatic" and not require a user to have to download it themselves: leads to more of a chance of people screwing up/getting frustrate.

To reduce friction, I thought it might be have a different repo (something like `chris-lovejoy/CodingForMedicineDatasets`), and then have a small straightforward section at the beginning of the notebook/call a helper function like the below:

```python
from pathlib import Path

stroke_data = Path("./data/stroke_data.zip")

if not stroke_data.exists():
    print("Getting data...")
    import urllib.request
    import shutil

    url = "https://raw.githubusercontent.com/lawrenceadams/recipes/main/stroke-prediction-dataset.zip"

    with urllib.request.urlopen(url) as response, open(stroke_data, 'wb') as file:
        shutil.copyfileobj(response, file)
```

Means we can pretty much guarantee it will work forever, and keeps the directory for each student quite clean. 

Or am I overcomplicating it? 😆

**Comment by lawrenceadams** [comment]
@medic-code Do you have any thoughts on how to best approach this?

**Comment by lawrenceadams** [comment]
Discussing with @chris-lovejoy will be best to let students learn how to fetch and handle data themselves

→ Manual Approach

**Comment by medic-code** [comment]
For what its worth, its better to encourage some self sufficiency in fetching and handling data.
